// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    [Migration("20180811021644_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication2.Entities.Chu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("A");

                    b.Property<int>("B");

                    b.Property<int>("C");

                    b.Property<int>("D");

                    b.HasKey("Id");

                    b.ToTable("Chus");
                });

            modelBuilder.Entity("WebApplication2.Entities.Foo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ManId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ManId");

                    b.ToTable("Foos");

                    b.HasData(
                        new { Id = 1, Name = "My Foo" }
                    );
                });

            modelBuilder.Entity("WebApplication2.Entities.Man", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChuId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ChuId");

                    b.ToTable("Mans");
                });

            modelBuilder.Entity("WebApplication2.Entities.Foo", b =>
                {
                    b.HasOne("WebApplication2.Entities.Man", "Man")
                        .WithMany()
                        .HasForeignKey("ManId");
                });

            modelBuilder.Entity("WebApplication2.Entities.Man", b =>
                {
                    b.HasOne("WebApplication2.Entities.Chu", "Chu")
                        .WithMany()
                        .HasForeignKey("ChuId");
                });
#pragma warning restore 612, 618
        }
    }
}
